### ISSUE TITLE
mails will not be deleted

### ISSUE THREAD

**Issue by tatoosh** [manolitto/joplin-mail-gateway#6]
```
function fetchMails {
    echo "Fetching mails"
    getmail_fetch ${GETMAIL_OPTS} -d -p ${POP3_PORT} ${POP3_HOST} "$1" "$2" "$3"
}
```

i added the delete flag: -d

now it's working

**Comment by manolitto** [comment]
Thanks for pointing this out.
Well, I did not recognize it because I am running my gmail account that I use as Joplin Inbox with the "archive mails on pop3 access" feature...  ;-)

Will add the -d flag as you suggested. Thanks

**Comment by manolitto** [comment]
added a comment suggesting the -d flag in the config
